### ISSUE TITLE
var_to_str() and str_to_var()

### ISSUE THREAD

**Issue by DanielSnd** [sirjoehighton/GodotToolkit#1]
Are you aware of the global scope methods var_to_str() and str_to_var()?

https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-method-var-to-str

https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-method-str-to-var

It seems like some of the methods you have could be done using them.

**Comment by sirjoehighton** [comment]
var_to_str() in the documentation shows that it would output in the following format
```
{
    "a": 1,
    "b": 2
}
```
As where array_to_string() in this toolkit intends to turn an array with string values and convert them to a plain continuous string with spaces between them, maybe i need to change the name of the function to make it more clear as to what this is intedned for.

**Comment by DanielSnd** [comment]
> var_to_str() in the documentation shows that it would output in the following format
> 
> ```
> {
>     "a": 1,
>     "b": 2
> }
> ```
> 
> As where array_to_string() in this toolkit intends to turn an array with string values and convert them to a plain continuous string with spaces between them, maybe i need to change the name of the function to make it more clear as to what this is intedned for.

Ah I see, I misunderstood.
The example you showed is turning a dictionary to string.

This is an example with an array:
```go
var array = ["Text", 5, 12.2, Vector2(3.2, 1.2)]
print( var_to_str(array) )
```
Output: ["Text", 5, 12.2, Vector2(3.2, 1.2)]

It doesn't output the info as just text with spaces between them, it outputs in the format above. But the cool thing is that it can do the other way around and take it from the format above back to the types they were.

But I now understand the purpose of your method is different xD no worries, I just thought I would point out these methods since I thought they had a similar purpose.
